version: '3.8'
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: shopsmart
      POSTGRES_USER: inderpreet
      POSTGRES_PASSWORD: Simr@7659
    ports:
      - "5432:5432"
  app:
    image: profile-service
    build:
      context: .
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/shopsmart
      SPRING_DATASOURCE_USERNAME: inderpreet
      SPRING_DATASOURCE_PASSWORD: Simr@7659
    depends_on:
      - db