apiVersion: v1
kind: ConfigMap
metadata:
  name: filebeat-config
data:
  filebeat.yml: |
    filebeat.inputs:
      - type: log
        enabled: true
        paths:
          - /var/log/profile-service/profile-service.log
        fields:
          service: profile-service

      - type: log
        enabled: true
        paths:
          - /var/log/utility-service/utility-service.log  # New log path for utility-service
        fields:
          service: utility-service

    output.logstash:
      hosts: ["logstash:5044"]
      ssl.enabled: false