apiVersion: apps/v1
kind: Deployment
metadata:
  name: logstash
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logstash
  template:
    metadata:
      labels:
        app: logstash
    spec:
      containers:
        - name: logstash
          image: docker.elastic.co/logstash/logstash:7.14.1
          ports:
            - containerPort: 5044
            - containerPort: 9600
          env:
            - name: LS_JAVA_OPTS
              value: "-Xmx512m -Xms512m"
          volumeMounts:
            - name: config-volume
              mountPath: /usr/share/logstash/pipeline/
      volumes:
        - name: config-volume
          configMap:
            name: logstash-config
            items:
              - key: logstash-profile-service.conf
                path: logstash.conf
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: logstash-config
data:
  logstash-profile-service.conf: |
    input {
      beats {
        port => 5044
        ssl => false
      }
    }
    
    filter {
      grok {
        match => { "message" => "%{TIME:time} \[%{WORD:thread}\] %{LOGLEVEL:loglevel} %{JAVACLASS:class} - %{GREEDYDATA:json_message}" }
        tag_on_failure => []
      }
    
      if "_grokparsefailure" in [tags] {
        grok {
          match => { "message" => "%{TIME:time} \[%{WORD:thread}\] %{LOGLEVEL:loglevel} %{JAVACLASS:class} - %{GREEDYDATA:logmessage}" }
          tag_on_failure => []
        }
      }
    
      if "_grokparsefailure" in [tags] {
        drop { }
      }
    }
    
    output {
      if [fields][service] == "profile-service" {
        elasticsearch {
          hosts => ["elasticsearch:9200"]
          index => "profile-service-logs"
          action => "create"
        }
      } else if [fields][service] == "utility-service" {
        elasticsearch {
          hosts => ["elasticsearch:9200"]
          index => "utility-service-logs"
          action => "create"
        }
      } else if [fields][service] == "central-hub" {
        elasticsearch {
          hosts => ["elasticsearch:9200"]
          index => "central-hub-logs"
          action => "create"
        }
      }else if [fields][service] == "product-service" {
        elasticsearch {
          hosts => ["elasticsearch:9200"]
          index => "product-service-logs"
          action => "create"
        }
      }else if [fields][service] == "order-service" {
        elasticsearch {
          hosts => ["elasticsearch:9200"]
          index => "order-service-logs"
          action => "create"
        }
      }
      stdout { codec => rubydebug }
      file {
        path => "/tmp/logstash.log"
        codec => rubydebug
      }
    }
  logstash.yml: |
    http.host: "0.0.0.0"
    http.port: 9600
    tcp.host: "0.0.0.0"
    tcp.port: 9600
---
apiVersion: v1
kind: Service
metadata:
  name: logstash
spec:
  selector:
    app: logstash
  ports:
    - protocol: TCP
      port: 5044
      targetPort: 5044