apiVersion: v1
kind: ConfigMap
metadata:
  name: logstash-config
data:
  logstash-profile-service.conf: |
    input {
        tcp {
            port => 5000
            codec => plain
            tags => ["tcp"]
        }
    }

    output {
        elasticsearch {
            hosts => ["elasticsearch:9200"]
            manage_template => false
            index => "profile-service-%{+YYYY.MM.dd}"  # Set a static index name
        }
        stdout { codec => rubydebug }
    }