name: DAST with OWASP ZAP

on:
  workflow_dispatch:

jobs:
  dast:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Run OWASP ZAP Baseline Scan on the deployed application
      - name: Run OWASP ZAP Baseline Scan
        uses: zaproxy/action-full-scan@v0.2.0
        with:
          target: 'http://192.168.49.2:30812'  # Replace with your application URL
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Upload ZAP DAST Report
      - name: Upload ZAP Scan Report
        uses: actions/upload-artifact@v2
        with:
          name: zap-report
          path: ./zap-output/