name: Security Scan (DAST)

on:
  push:
    branches: [main, feature/*]
  pull_request:
    branches: [main]
  schedule:
    - cron: '0 0 * * 0'  # Weekly scan on Sundays

jobs:
  security_scan:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean package

      # Step 1: Create Docker network
      - name: Create Docker Network
        run: docker network create zap-network

      # Step 2: Build the Docker image for the profile-service
      - name: Build Docker Image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: false
          tags: profile-service:latest

      # Step 3: Run the Docker container for the application in the zap-network
      - name: Run Docker Container
        run: docker run -d --name profile-service --network zap-network -p 8080:80 profile-service:latest

      # Step 4: Wait for the application to start and be available
      - name: Wait for Application to Start
        run: |
          echo "Waiting for the application to start..."
          timeout 300 bash -c 'while [[ "$(curl -s -o /dev/null -w ''%{http_code}'' localhost:8080/actuator/health)" != "200" ]]; do sleep 5; done' || exit 1

      # Step 5: Run ZAP Full Scan in the same Docker network
      - name: ZAP Full Scan
        uses: zaproxy/action-full-scan@v0.11.0
        with:
          target: 'http://profile-service:80'
          token: ${{ secrets.GITHUB_TOKEN }}
          cmd_options: >
            -t http://profile-service:80
            -r zap_report.html
            -z "-config scanner.attackStrength=HIGH 
                -config scanner.alertThreshold=MEDIUM
                -config view.mode=attack
                -config api.disablekey=true
                -config rules.cookie.ignorelist=true
                -config scanner.level=ATTACK
                -config rules.ascanrules.refs.json=true
                -config rules.ascanrules.script.injection=true
                -config rules.ascanrules.server.side.injection=true
                -config rules.ascanrules.sql.injection=true
                -config rules.ascanrules.nosqli.injection=true
                -config rules.ascanrules.xxe.injection=true
                -config rules.ascanrules.path.traversal=true
                -config rules.ascanrules.remote.code.execution=true"

      # Step 6: Upload the ZAP report as an artifact
      - name: Upload Security Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: zap-security-report
          path: zap_report.html

      # Fail on critical findings
      - name: Check ZAP Report
        if: always()
        run: |
          if grep -q "Critical\|High" zap_report.html; then
            echo "Critical or High severity vulnerabilities found!"
            exit 1
          fi